// src/lib/containers/auth-form.svelte
<script context="module" lang="ts">
	export type OnSubmitAuth = (values: { email: string; password: string }) => void;
</script>

<script lang="ts">
	import type { ApiError } from '$lib/api/schemas';
	import Button from '$lib/components/button.svelte';
	import ErrorMessage from '$lib/components/error-message.svelte';
	import Field from '$lib/components/field.svelte';

	export let submitText: string;
	export let onSubmit: OnSubmitAuth;
	export let isLoading: boolean;
	export let isError: boolean;
	export let error: ApiError | null;
	export let isSuccess: boolean;

	let email: string;
	let password: string;
</script>

<form
	class="flex flex-col rounded-2xl gap-y-6"
	on:submit|preventDefault={() => onSubmit({ email, password })}
>
	<Field
		label="Email"
		placeholder="example@email.com"
		type="email"
		name="email"
		required
		bind:value={email}
	/>
	<Field
		label="Password"
		placeholder="at least 8 characters"
		type="password"
		name="password"
		required
		minlength={8}
		bind:value={password}
	/>

	<div class="flex flex-col gap-4">
		<Button type="submit" {isLoading} {isError} {isSuccess}>{submitText}</Button>
		{#if error}
			<ErrorMessage>{error.message}</ErrorMessage>
		{/if}
	</div>
</form>

// src/features/account/auth-form.tsx
import { createForm } from "@features/form"
import { Button, ErrorMessage, Field, Heading, Title } from "@features/ui"
import { Component, JSX } from "solid-js"
import { z } from "zod"

interface AuthFormValues {
	email: string
	password: string
}

interface AuthFormProps {
	title: string
	subtitle: JSX.Element
	submitText: string
	onSubmit: (values: AuthFormValues) => void
	isLoading: boolean
	error?: string
}

const schema = z.object({
	email: z.string().email(),
	password: z.string().min(8),
})

export const AuthForm: Component<AuthFormProps> = (props) => {
	const form = createForm({
		defaultValues: { email: "", password: "" },
		schema,
	})

	return (
		<form
			class="flex flex-col gap-6 max-w-xs grow mt-28 mx-auto"
			onSubmit={form.handleSubmit((values) => props.onSubmit(values))}
		>
			<div class="flex justify-between items-center">
				<Heading as="h2">{props.title}</Heading>
				<Title>{props.subtitle}</Title>
			</div>
			<Field type="email" label="Email" name="email" control={form.control} />
			<Field type="password" label="Password" name="password" control={form.control} />
			<Button type="submit" isLoading={props.isLoading}>
				{props.submitText}
			</Button>
			<ErrorMessage>{props.error}</ErrorMessage>
		</form>
	)
}
