// src/features/ui/button.tsx
import { Component, mergeProps, Show } from "solid-js"

interface ButtonProps {
	type?: "button" | "submit"
	isLoading?: boolean
}

export const Button: Component<ButtonProps> = (baseProps) => {
	const props = mergeProps({ type: "button" }, baseProps)

	return (
		<button
			type={props.type}
			class="bg-primary text-secondary flex items-center justify-center rounded h-9 border border-primary transition"
			classList={{
				"cursor-wait": props.isLoading,
				"hover:text-primary hover:bg-secondary": !props.isLoading,
			}}
			disabled={props.isLoading}
		>
			<Show when={!props.isLoading} fallback={<Loading />}>
				{props.children}
			</Show>
		</button>
	)
}

const Loading: Component = () => {
	return <i class="bi bi-arrow-clockwise animate-spin" />
}

// src/lib/components/button.svelte
<script lang="ts">
	type Type = 'button' | 'submit' | 'reset' | 'menu';

	let className: string = '';
	export { className as class };
	export let type: Type = 'button';
	export let isLoading = false;
	export let isError = false;
	export let isSuccess = false;
</script>

<button
	class={`px-6 disabled:cursor-not-allowed bg-primary text-background font-semibold py-2 hover:opacity-95 disabled:hover:opacity-100 ${className}`}
	disabled={isLoading || isError || isSuccess}
	{type}
	on:click
>
	{#if isLoading}
		<i class="bi bi-arrow-clockwise inline-block animate-spin" />
	{:else if isError}
		<i class="bi bi-x-circle" />
	{:else if isSuccess}
		<i class="bi bi-check-circle" />
	{:else}
		<slot />
	{/if}
</button>
