// src/features/ui/field.tsx
import { Component, mergeProps } from "solid-js"

interface FieldProps {
	label: string
	type?: "text" | "email" | "password"
}

export const Field: Component<FieldProps> = (baseProps) => {
	const props = mergeProps({ type: "text" }, baseProps)

	return (
		<div class="flex flex-col">
			<label class="text-sm text-muted" for={props.label}>
				{props.label}
			</label>
			<input
				class="bg-primary/5 rounded px-2 py-1 text-base border-none"
				id={props.label}
				type={props.type}
			/>
		</div>
	)
}

// src/lib/components/field.svelte
<script lang="ts">
	type Type = 'text' | 'email' | 'password';

	export let label: string;
	export let type: Type = 'text';
	export let placeholder: string = '';
	export let name: string;
	export let required: boolean = false;
	export let value: string = '';
	export let minlength: number | undefined = undefined;
</script>

<label class="flex flex-col text-sm gap-1">
	{label}
	<input
		class="focus:ring-primary focus:border-primary"
		{placeholder}
		{name}
		{required}
		bind:value
		{minlength}
		{...{ type }}
	/>
</label>
